# Generated by Django 4.1.1 on 2022-10-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
