# Generated by Django 4.1.1 on 2022-10-16 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_category_listing_delete_categories_delete_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchList",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
