# Generated by Django 4.1.1 on 2022-10-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_owner_alter_listing_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="auctions.category",
            ),
        ),
    ]
